# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/images'
    promotions_directory: '%kernel.project_dir%/public/uploads/promotions'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Migrations/'  # Add this line to exclude migrations in src/

    # explicitly configure the service
    DoctrineMigrations\:
        resource: '../migrations/'
        tags: ['doctrine.migration']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Twig\RestaurantExtension:
        # Autowiring for Twig extensions
        autowire: true
        tags: ['twig.extension']

    App\Service\ImageUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'
            
    # Pass the project directory to the command
    App\Command\ImportSampleImagesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
            
    App\Command\FixMappingIssuesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
