# This file should be deleted or commented out as it's causing the duplicate registration
# services:
#    _defaults:
#        public: false
#        autowire: true
#        autoconfigure: true
#
#    # Register the StringExtension with auto configuration
#    Twig\Extra\String\StringExtension: ~
